version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: "chore"
    directory: /tests/unit/
    package-ecosystem: pip
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
